services:
  nginx:
    image: "nginx:1.27"
    ports:
      - "5200:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  ui:
    image: paloma
    entrypoint: project
    environment:
      PROJECT_PATH: ./packages/nevada-ui
      PROJECT_COMMAND: staticwww:dev
      PORT: "5201"
    ports:
      - "5201:5201"
    volumes:
      # iac/images/compose/$PWD
      - "../../../..:/workspace"
  http:
    image: paloma
    entrypoint: project
    environment:
      PROJECT_PATH: ./packages/nevada-io
      PROJECT_COMMAND: http:dev
      PORT: "5202"
    ports:
      - "5202:5202"
    volumes:
      - "../../../..:/workspace"      
  http-canary:
    image: paloma
    entrypoint: project
    environment:
      PROJECT_PATH: ./packages/nevada-io
      PROJECT_COMMAND: http:canary
    volumes:
      - "../../../..:/workspace"
      - "/tmp/paloma-nevada-io-canary:/tmp"
    depends_on:
      - http
  # minio:
  #   image: "minio:17"